package mainProjekt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class MemoryAnalysisrating {
    private static MemoryAnalysisrating INSTANCE;
    private static final String CREATE_TABLE = "CREATE TABLE company(AnalysisRatingName varchar GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY , " +
            "id float (20)  unique , Companyname_AnalysisRating varchar (20) not null ,Eigenkapitalrendite float(11),EBITMarge float(11),Eigenkapitalquote float(11),KursGewinnVerhaeltnis float(11),KursGewinnVerhaeltnisAktuell float(11),Analystenmeinungen float(11),ReaktionaufQuartalszahlen float(11),Gewinnrevision float(11),Kursverlauf6Monate float(11),Kursverlauf12Monate float(11),Kursmomentum float(11),Dreimonatsreversal float(11),Gewinnwachstum float(11),;";

    private MemoryAnalysisrating(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mavenjavafxcompany?useSSL=false&serverTimezone=UTC", "MavenJFX", "mavenjfx");
            Statement stmnt = conn.createStatement();
            stmnt.execute(CREATE_TABLE);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public synchronized static MemoryAnalysisrating getInstance(){
        if(INSTANCE == null){
            INSTANCE = new MemoryAnalysisrating();
        }
        System.out.println("Got Instance as : " + INSTANCE);
        return INSTANCE;
    }
}
