package mainProjekt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class MemoryAnalysissteps {
    private static MemoryAnalysissteps INSTANCE;
    private static final String CREATE_TABLE = "CREATE TABLE analysissteps(AnalysisStepsName varchar GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY , " +
            "id float (20)  unique ,Companyname_AnalysisSteps varchar (20) not null, Eigenkapitalrendite float(11),\n" +
            "                             EBITMarge float(11),\n" +
            "                             Eigenkapitalquote float(11),\n" +
            "                             KursGewinnVerhaeltnis float(11),\n" +
            "                             KursGewinnVerhaeltnisAktuell float(11),\n" +
            "                             Analystenmeinungen float(11),\n" +
            "                             ReaktionaufQuartalszahlen float(11),\n" +
            "                             Gewinnrevision float(11),\n" +
            "                             Kursverlauf6Monate float(11),\n" +
            "                             Kursverlauf12Monate float(11),\n" +
            "                             Kursmomentum float(11),\n" +
            "                             Dreimonatsreversal float(11),\n" +
            "                             Gewinnwachstum float(11),;";

    private MemoryAnalysissteps(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mavenjavafxcompany?useSSL=false&serverTimezone=UTC", "MavenJFX", "mavenjfx");
            Statement stmnt = conn.createStatement();
            stmnt.execute(CREATE_TABLE);
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public synchronized static MemoryAnalysissteps getInstance(){
        if(INSTANCE == null){
            INSTANCE = new MemoryAnalysissteps();
        }
        System.out.println("Got Instance as : " + INSTANCE);
        return INSTANCE;
    }
}
